### PR TITLE
Start/End Date Options

### PR DESCRIPTION
**Pull request by mrvnmchm**
Added options for start and end dates, with defaults configured. Will be following up with more testing in separate PR.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Thanks, @mrvnmchm looks good. Can you please add one simple test with a start/end date before I merge this?

**Comment by mrvnmchm** [comment]
Added test for the default dates being generated and updated other tests to include date values (default start/end).  Let me know if I am missing anything. 👍 
```python
    @classmethod
    def test_default_start_end_date(self):
        """ Verify Start Date """
        try:
            s: str = b.default_start_date()
            e: str = b.default_end_date()
            # Assertions
            assert b.valid_date(s)
            assert b.valid_date(e)
        except Exception as err:
            raise ValueError(err)

    @classmethod
    def test_get_excel(self):
        """ Verify excel output """
        try:
            b.get_data(
                rooms,
                country,
                out_format="excel",
                start_date=b.default_start_date(),
                end_date=b.default_end_date(),
            )
            assert os.path.isfile("hotels-in-{}.xls".format(country))
        except IOError:
            print("Failure: File cannot be read.")
```

**Comment by mrvnmchm** [comment]
Also had added the validation on the arguments.
```shell
(env) ~/Documents/Documents - MacBook Pro/DEV/bookingScraper/BookingScraper on master*
$ python booking.py -s '2020-10-30' -e 'ahdpaiohfa'
usage: booking.py [-h] [-r [ROOMS]] [-c [COUNTRY]] [-o [{json,excel,csv}]] [-s STARTDATE] [-e ENDDATE]
booking.py: error: argument -e/--enddate: ahdpaiohfa is not a valid date.
```

**Review by ZoranPandovski — APPROVED** [review]
Perfect, thanks

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
